import {
    BlogPost,
    EventItem,
    NotificationItem,
    MediaItem,
    AnnouncementItem,
  } from "@/types/editorPanel";
  
  export const mockBlogs: BlogPost[] = [
    {
      id: "blog-1",
      title: "MG İçin Yeni Tedavi Seçenekleri",
      category: "Sağlık",
      publishedAt: "2023-01-01",
      status: "published",
      author: "Editor 1",
      summary: "MG alanındaki güncel tedavi yaklaşımlarını özetleyen bilgilendirici içerik.",
      bodyMarkdown: "",
    },
    {
      id: "blog-2",
      title: "Yıllık Bağış Kampanyası Öne Çıkanlar",
      category: "Topluluk",
      publishedAt: "2023-01-01",
      status: "published",
      author: "Editor 1",
      summary: "Yıllık bağış kampanyasında öne çıkan gelişmeler ve sonuçlar.",
      bodyMarkdown: "",
    },
    {
      id: "blog-3",
      title: "İstanbul’da MG Farkındalık Etkinliği",
      category: "Etkinlik",
      publishedAt: "2023-01-01",
      status: "published",
      author: "Editor 1",
      summary: "İstanbul’da düzenlenen farkındalık etkinliğine dair kısa özet.",
      bodyMarkdown: "",
    },
    {
      id: "blog-4",
      title: "Yeni Gönüllü Programı Duyurusu",
      category: "Duyuru",
      publishedAt: "2026-04-04",
      status: "draft",
      author: "Editor 1",
      summary: "Yeni gönüllü programı için hazırlanan taslak gönderi.",
      bodyMarkdown: "",
    },
    {
      id: "blog-5",
      title: "Hasta Destek Rehberi Taslağı",
      category: "Destek",
      publishedAt: "2026-04-05",
      status: "draft",
      author: "Editor 1",
      summary: "Hasta ve yakınları için hazırlanan destek rehberi taslağı.",
      bodyMarkdown: "",
    },
  ];
  
  export const mockEvents: EventItem[] = [
    {
      id: "event-1",
      title: "İstanbul MG Farkındalık Etkinliği",
      date: "2026-05-05",
      endDate: "2026-05-05",
      location: "İstanbul Toplum Merkezi",
      city: "İstanbul",
      venue: "Toplum Merkezi",
      type: "Farkındalık",
      capacity: 120,
      isOnline: false,
      status: "planned",
    },
    {
      id: "event-2",
      title: "İzmir MG Farkındalık Etkinliği",
      date: "2026-07-17",
      endDate: "2026-07-17",
      location: "İzmir Toplum Merkezi",
      city: "İzmir",
      venue: "Toplum Merkezi",
      type: "Webinar",
      capacity: 90,
      isOnline: false,
      status: "planned",
    },
    {
      id: "event-3",
      title: "Ankara Destek Grubu Toplantısı",
      date: "2026-08-19",
      endDate: "2026-08-19",
      location: "Ankara Toplum Merkezi",
      city: "Ankara",
      venue: "Toplum Merkezi",
      type: "Destek Grubu",
      capacity: 60,
      isOnline: false,
      status: "planned",
    },
    {
      id: "event-4",
      title: "Hasta Hakları Webinarı",
      date: "2026-09-10",
      endDate: "2026-09-10",
      location: "Online",
      city: "Online",
      venue: "Zoom",
      type: "Webinar",
      capacity: 200,
      isOnline: true,
      status: "planned",
    },
  ];
  
  export const mockNotifications: NotificationItem[] = [
    {
      id: "n1",
      title: "Yeni blog yazısı taslağı oluşturuldu.",
      isRead: false,
      createdAt: "2026-04-06T10:00:00",
    },
    {
      id: "n2",
      title: "Bir etkinlik güncellendi.",
      isRead: false,
      createdAt: "2026-04-06T11:00:00",
    },
    {
      id: "n3",
      title: "Medya öğesi başarıyla yüklendi.",
      isRead: true,
      createdAt: "2026-04-05T14:30:00",
    },
  ];
  
  export const mockMedia: MediaItem[] = [
    {
      id: "media-1",
      pageKey: "home-slider",
      title: "Ana Sayfa Slider 1",
      description: "Ana sayfada kullanılan slider görseli.",
      tags: ["slider", "anasayfa"],
      visibility: "public",
      featured: true,
      imageUrl:
        "https://images.unsplash.com/photo-1576091160550-2173dba999ef?q=80&w=1200&auto=format&fit=crop",
      createdAt: "2026-04-07T08:00:00",
    },
    {
      id: "media-2",
      pageKey: "about-gallery",
      title: "Hakkımızda Galerisi 1",
      description: "Destek çalışmaları görseli.",
      tags: ["hakkımızda"],
      visibility: "public",
      featured: false,
      imageUrl:
        "https://images.unsplash.com/photo-1584515933487-779824d29309?q=80&w=1200&auto=format&fit=crop",
      createdAt: "2026-04-07T08:10:00",
    },
    {
      id: "media-3",
      pageKey: "blog-gallery",
      title: "Blog Galerisi 1",
      description: "Blog detay görseli.",
      tags: ["blog"],
      visibility: "public",
      featured: false,
      imageUrl:
        "https://images.unsplash.com/photo-1530026405186-ed1f139313f8?q=80&w=1200&auto=format&fit=crop",
      createdAt: "2026-04-07T08:20:00",
    },
  ];
  
  export const mockAnnouncements: AnnouncementItem[] = [
    {
      id: "announcement-1",
      title: "Nisan Ayı Destek Toplantısı Duyurusu",
      content: "Nisan ayı destek toplantımız bu hafta sonu gerçekleştirilecektir.",
      audience: "all",
      publishedAt: "2026-04-08",
      status: "published",
      pinned: true,
    },
    {
      id: "announcement-2",
      title: "Gönüllü Eğitim Programı",
      content: "Yeni gönüllüler için eğitim programı kayıtları açılmıştır.",
      audience: "volunteers",
      publishedAt: "2026-04-10",
      status: "published",
      pinned: false,
    },
    {
      id: "announcement-3",
      title: "Üyelik Yenileme Hatırlatması",
      content: "Dernek üyelik yenileme süreci bu ay sonunda tamamlanacaktır.",
      audience: "members",
      publishedAt: "2026-04-12",
      status: "draft",
      pinned: false,
    },
  ];